name: Cypress Tests

on: [push, workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      # checkout the repo into our pipeline
      - name: Checkout
        uses: actions/checkout@v4
      # install npm deps, cache them
      # and run all Cypress tests
      - name: Cypress info
        uses: cypress-io/github-action@v6
        with:
          build: npm --version
          start: node --version
